name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18

      # - name: Install dependencies
      #   run: |
      #     corepack enable
      #     pnpm install --frozen-lockfile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ toLower(github.actor) }}/kromka-app:prod
          build-args: |
            DATABASE_URI=${{ secrets.DATABASE_URI }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
            AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
            EMAIL_SERVER=${{ secrets.EMAIL_SERVER }}
            EMAIL_FROM=${{ secrets.EMAIL_FROM }}
            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}
            NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
            NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
            NEXT_PUBLIC_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
          # secrets: |
          #   NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          #   DATABASE_URI=${{ secrets.DATABASE_URI }}
          #   PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
          #   AUTH_SECRET=${{ secrets.AUTH_SECRET }}
          #   AUTH_GOOGLE_ID=${{ secrets.AUTH_GOOGLE_ID }}
          #   AUTH_GOOGLE_SECRET=${{ secrets.AUTH_GOOGLE_SECRET }}
          #   NEXT_PUBLIC_MAPS_API_KEY=${{ secrets.NEXT_PUBLIC_MAPS_API_KEY }}
          #   EMAIL_SERVER=${{ secrets.EMAIL_SERVER }}
          #   EMAIL_FROM=${{ secrets.EMAIL_FROM }}
          #   EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          #   EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          #   AUTH_RESEND_KEY=${{ secrets.AUTH_RESEND_KEY }}
          #   NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${{ secrets.NEXT_PUBLIC_STRIPE_PUBLIC_KEY }}
          #   STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}